name: Multi Environment in CI/CD
on: [push]
jobs:
 test-suite:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Run Automated tests
     run:  | 
       echo "Running unit and integrating tests"
       sleep 3
       echo "Tests passed"
 onebox:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - name: Deploy to onebox
        run:  |
          echo "Deploying to onebox"
          sleep 3
          echo "Deployed successfully to onebox"
 staging:
     runs-on: ubuntu-latest
     needs: onebox
     steps:
       - name: Deploy to staging
         run:  |
           echo "Deplyoing to staging"
           sleep 3
           echo "Deployed successfully to staging"
 production:
     runs-on: ubuntu-latest
     needs: staging
     steps:
       - name: Deploy to production
         run:  |
           echo "Deploying to production"
           sleep 3
           echo "Deployed successfully to production..."
  
